name: Create Release

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    name: Create Release
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
          
      - name: Build executable
        run: |
          python build.py
          
      - name: Create Release Directory
        run: |
          mkdir -p release
          copy PO_Formatter.exe release\PO_Formatter_${{ github.ref_name }}.exe
          copy amain_fix.py release\
          
      - name: Create CHANGELOG
        run: |
          echo "# PO Formatter ${{ github.ref_name }} Release Notes" > release\CHANGELOG.md
          echo "" >> release\CHANGELOG.md
          echo "## Bug Fixes" >> release\CHANGELOG.md
          echo "" >> release\CHANGELOG.md
          echo "- **AMAIN Format:** Fixed 'Invalid quantity found: Sku,Qty' error by removing headers from CSV and tab-delimited output formats" >> release\CHANGELOG.md
          echo "- **Traxxas Format:** Added support for the new template format with variant field for color options" >> release\CHANGELOG.md
          echo "" >> release\CHANGELOG.md
          echo "## New Features" >> release\CHANGELOG.md
          echo "" >> release\CHANGELOG.md
          echo "- **Traxxas Variants:** Automatically detects and extracts color variants from SKUs (like -RED, -GRN, -BLUE)" >> release\CHANGELOG.md
          echo "- **Standalone AMAIN Fixer:** Added simple amain_fix.py script to quickly process files for users without rebuilding the executable" >> release\CHANGELOG.md
          
      - name: Create ZIP Archive
        run: |
          cd release
          Compress-Archive -Path * -DestinationPath ..\PO_Formatter_${{ github.ref_name }}.zip
          cd ..
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-files
          path: |
            PO_Formatter_${{ github.ref_name }}.zip
            PO_Formatter.exe
          
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            PO_Formatter_${{ github.ref_name }}.zip
            PO_Formatter.exe
          name: PO Formatter ${{ github.ref_name }}
          body_path: release/CHANGELOG.md
          draft: false
          prerelease: false 